### ISSUE TITLE
resume error

### ISSUE THREAD

**Issue by ChenYingpeng** [michuanhaohao/reid-strong-baseline#114]
Error happened when run below code.

`bash Experiment-pretrain_choice-all_tricks-tri_center.sh`

This is my Experiment-pretrain_choice-all_tricks-tri_center.sh.

`python3 tools/train.py --config_file='configs/softmax_triplet_with_center.yml' MODEL.DEVICE_ID "('0')" DATASETS.NAMES "('xxxx')" DATASETS.ROOT_DIR "('/home/ss/person-reid/data')" MODEL.PRETRAIN_CHOICE "('self')" MODEL.PRETRAIN_PATH "('/home/ss/person-reid/reid-strong-baseline/output/resnet50_ibn_a_model_400.pth')" OUTPUT_DIR "('/home/ss/person-reid/reid-strong-baseline/output/Experiment-all-tricks-tri_center-384x192-bs8x4-warmup10-erase0_5-labelsmooth_on-laststride1-bnneck_on-triplet_centerloss0_0005)"`

Error log as below.

`2019-11-27 16:02:16,026 reid_baseline.train INFO: Start training
/usr/local/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:100: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 113, in train
    start_epoch     # add for using self trained model
  File "/home/ss/person-reid/reid-strong-baseline/engine/trainer.py", line 291, in do_train_with_center
    trainer.run(train_loader, max_epochs=epochs)
  File "/usr/local/lib/python3.7/site-packages/ignite/engine/engine.py", line 446, in run
    self._handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/usr/local/lib/python3.7/site-packages/ignite/engine/engine.py", line 433, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/usr/local/lib/python3.7/site-packages/ignite/engine/engine.py", line 399, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/usr/local/lib/python3.7/site-packages/ignite/engine/engine.py", line 391, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "/home/ss/person-reid/reid-strong-baseline/engine/trainer.py", line 89, in _update
    optimizer.step()
  File "/usr/local/lib/python3.7/site-packages/torch/optim/lr_scheduler.py", line 51, in wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/optim/adam.py", line 95, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: expected device cpu but got device cuda:0`
How to solve it? Thanks for you in advance.

**Comment by michuanhaohao** [comment]
Try to use pytorch1.0. There are some differences between pytorch1.1 and pytorch1.0.

Or you can read this carefully:

 Detected call of lr_scheduler.step()beforeoptimizer.step(). In PyTorch 1.1.0 and later, you should call them in the opposite order: _**optimizer.step() before lr_scheduler.step()**_.

**Comment by ChenYingpeng** [comment]
I reinstall pytorch1.0.0 and retrain with imagenet pretrained model after 5 epochs.
Error happened as below.
`2019-11-27 17:54:20,835 reid_baseline.train INFO: Start training
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 113, in train
    start_epoch     # add for using self trained model
  File "/home/ss/person-reid/reid-strong-baseline/engine/trainer.py", line 303, in do_train_with_center
    trainer.run(train_loader, max_epochs=epochs)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 446, in run
    self._handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 433, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 399, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 391, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "/home/ss/person-reid/reid-strong-baseline/engine/trainer.py", line 93, in _update
    optimizer.step()
  File "/usr/local/lib/python3.5/dist-packages/torch/optim/adam.py", line 93, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor`

**Comment by michuanhaohao** [comment]
' RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor'

You compute a CPU tensor in a GPU device. Please debug them by yourself first. Your bugs are simple problems of pytorch.

**Comment by ChenYingpeng** [comment]
@michuanhaohao The error is mainly caused by this code, which is `optimizer.step()` in trainer.py.
I checked all related code and didn't find code exception. It was nomal with 'imagenet' mode in training ,but error happened with 'self' mode.I also compared the data format of optimizer,which is the same, in the two modes. How to solve it? Thanks for you in advance.

**Comment by ChenYingpeng** [comment]
@michuanhaohao I have solved this problem. we must convert the resumed state data of optimizer to gpu.You could add these code into trainer.py.

    
    if device: 
        if torch.cuda.device_count() > 1:
            model = nn.DataParallel(model)
        model.to(device)  
        #add below code 
        for state in optimizer.state.values():  
            for k,v in state.items():
                if isinstance(v,torch.Tensor):
                    state[k] = v.cuda() 

For more detail,please look this [[link]](https://github.com/jwyang/faster-rcnn.pytorch/issues/222).
