### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Vincent630** [michuanhaohao/reid-strong-baseline#122]
i did as readme says,but i get this problem,i will be appreciate it if you can help me 
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 27, in train
    train_loader, val_loader, num_query, num_classes = make_data_loader(cfg)
  File "/home/suning/19049300/reid-strong-baseline/data/build.py", line 16, in make_data_loader
    train_transforms = build_transforms(cfg, is_train=True)
  File "/home/suning/19049300/reid-strong-baseline/data/transforms/build.py", line 17, in build_transforms
    T.RandomHorizontalFlip(p=cfg.INPUT.PROB),
TypeError: object() takes no parameters

**Comment by fenglin218** [comment]
I has get this problem also

**Comment by lightingstars** [comment]
have you solved this question ? I aslo have met the question ,too.
apperaciate to you reply .

**Comment by lightingstars** [comment]
I have solved this problem 
you only need to change
 T.RandomHorizontalFlip(p=cfg.INPUT.PROB),
to 
T.RandomHorizontalFlip()
