### ISSUE TITLE
Train error with imagenet 

### ISSUE THREAD

**Issue by Zhangzhengyi-up** [michuanhaohao/reid-strong-baseline#158]
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 30, in train
    model = build_model(cfg, num_classes)
  File "./modeling/__init__.py", line 13, in build_model
    model = Baseline(num_classes, cfg.MODEL.LAST_STRIDE, cfg.MODEL.PRETRAIN_PATH, cfg.MODEL.NECK, cfg.TEST.NECK_FEAT, cfg.MODEL.NAME, cfg.MODEL.PRETRAIN_CHOICE)
  File "./modeling/baseline.py", line 132, in __init__
    self.base.load_param(model_path)
  File "/home/zzy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __getattr__
    type(self).__name__, name))
AttributeError: 'Baseline' object has no attribute 'base'

**Comment by michuanhaohao** [comment]
What is your cfg.MODEL.NAME?

**Comment by Zhangzhengyi-up** [comment]
In config ,   _C.MODEL.NAME = 'imagenet'

**Comment by michuanhaohao** [comment]
'MODEL.NAME' means the backbone, such as 'resnet50', 'resnet101', etc.

**Comment by Zhangzhengyi-up** [comment]
Thanks.I'm new to person re-ID.My problem has been solved.
