### ISSUE TITLE
Error after 40 epoch

### ISSUE THREAD

**Issue by zhukuan96** [michuanhaohao/reid-strong-baseline#17]
Hi, I just run the Experiment-all_tricks-tri_center-market.sh, but it raise an error after 40 epoch. I am a fresh man so I do not know how it happen. Thank you~
2019-04-11 20:56:45,254 reid_baseline.train INFO: Epoch[40] Iteration[60/186] Loss: 1.312, Acc: 0.984, Base Lr: 3.50e-04
Traceback (most recent call last):
  File "tools/train.py", line 155, in <module>
    main()
  File "tools/train.py", line 151, in main
    train(cfg)
  File "tools/train.py", line 110, in train
    start_epoch     # add for using self trained model
  File "./engine/trainer.py", line 274, in do_train_with_center
    trainer.run(train_loader, max_epochs=epochs)
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 359, in run
    self._handle_exception(e)
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 324, in _handle_exception
    raise e
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 350, in run
    self._fire_event(Events.EPOCH_COMPLETED)
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 259, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/handlers/checkpoint.py", line 172, in __call__
    self._save(obj=obj, path=path)
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/handlers/checkpoint.py", line 130, in _save
    self._internal_save(obj, tmp.file)
  File "/home/zhukuan/local/anaconda3/lib/python3.6/site-packages/ignite/handlers/checkpoint.py", line 144, in _internal_save
    raise ValueError("Object should have `state_dict` method.")
ValueError: Object should have `state_dict` method.

**Comment by he010103** [comment]
@michuanhaohao I met the same problem!

**Comment by he010103** [comment]
@zhukuan96 [https://github.com/michuanhaohao/reid-strong-baseline/blob/cfc5e9e17a75acb4c1d3fa16bea2ef0894ca21da/engine/trainer.py#L150](url)
delete the `state_dict()` can fix the issue.

**Comment by michuanhaohao** [comment]
@he010103 @zhukuan96 Thank for your discussion. We have not encountered this problem yet.

**Comment by zhukuan96** [comment]
@he010103 thank you！I fix the issue by delete all state_dict() in ./engine/trainer.py

**Comment by prismformore** [comment]
@he010103   I need to delete all `.sttate_dict() ` in ./engine/trainer.py or it would fail when training with center loss.

@michuanhaohao According to the latest ignite [docs](https://github.com/michuanhaohao/reid-strong-baseline/blob/f5b25b4ba94fc20e4a3fa3748e22f3af543b64b4/engine/trainer.py#L157), `trainer.add_event_handler` in [./engine/trainer.py](https://github.com/michuanhaohao/reid-strong-baseline/blob/f5b25b4ba94fc20e4a3fa3748e22f3af543b64b4/engine/trainer.py#L157) takes  `model` instead of ` model.state_dict()` as input. This may be a ignite version problem and I think it need some modification.
