### ISSUE TITLE
预训练后的模型再次训练报错AttributeError: 'Baseline' object has no attribute 'copy' 


### ISSUE THREAD

**Issue by GJTNB** [michuanhaohao/reid-strong-baseline#172]
AttributeError: 'Baseline' object has no attribute 'copy' 
请问这个错误到底怎么解决，我看很多人都有这个错误，但是好像没有准确的回答。

**Comment by Simplesss** [comment]
I tried the following conversion
model.load_ state_ dict( torch.load ( cfg.MODEL.PRETRAIN_ PATH).state_ dict()) 
optimizer.load_ state_ dict( torch.load (path_ To_ optimizer).state_ dict())

The model can be loaded normally, but there are problems during training,
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    train(cfg)
  File "tools/train.py", line 71, in train
    start_epoch     # add for using self trained model
  File "/media/ss/38cfe914-26f2-4a22-9cf1-bea9684775ac/ZhiChao_Cui/Code/reid-strong-baseline/engine/trainer.py", line 208, in do_train
    trainer.run(train_loader, max_epochs=epochs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 326, in run
  File "/usr/local/python3.6/lib/python3.6/site-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 291, in _handle_exception
  File "/usr/local/python3.6/lib/python3.6/site-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 313, in run
  File "/usr/local/python3.6/lib/python3.6/site-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 280, in _run_once_on_dataset
  File "/usr/local/python3.6/lib/python3.6/site-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 291, in _handle_exception
  File "/usr/local/python3.6/lib/python3.6/site-packages/pytorch_ignite-0.1.2-py3.6.egg/ignite/engine/engine.py", line 272, in _run_once_on_dataset
  File "/media/ss/38cfe914-26f2-4a22-9cf1-bea9684775ac/ZhiChao_Cui/Code/reid-strong-baseline/engine/trainer.py", line 49, in _update
    optimizer.step()
  File "/usr/local/python3.6/lib/python3.6/site-packages/torch/optim/adam.py", line 93, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: expected backend CPU and dtype Float but got backend CUDA and dtype Float.

How did you solve it?

**Comment by Simplesss** [comment]
I've solved this problem by convert

model.load_ state_ dict( torch.load ( cfg.MODEL.PRETRAIN_ PATH))
optimizer.load_ state_ dict( torch.load (path_ To_ optimizer))
to
model = torch.load ( cfg.MODEL.PRETRAIN_ PATH)
optimizer = torch.load (path_ To_ optimizer)

**Comment by LY-cmd-xtt** [comment]
Train with center loss, the loss type is triplet_center
label smooth on, numclasses: 751
Start epoch: 120
Path to the checkpoint of optimizer:.../下载/reid-strong-baseline-master/market_sj/resnet50_optimizer_120.pth
Path to the checkpoint of center_param:.../下载/reid-strong-baseline-master/market_sj/resnet50_center_param_120.pth
Path to the checkpoint of optimizer_center:.../下载/reid-strong-baseline-master/market_sj/resnet50_optimizer_center_120.pth
2021-05-20 21:50:43,499 reid_baseline.train INFO: Start training
Process finished with exit code 0
为什么我按照这样改了后，直接从最后一个epoch开始，然后直接结束训练了？

**Comment by LY-cmd-xtt** [comment]
@Simplesss 
Train with center loss, the loss type is triplet_center
label smooth on, numclasses: 751
Start epoch: 120
Path to the checkpoint of optimizer:.../下载/reid-strong-baseline-master/market_sj/resnet50_optimizer_120.pth
Path to the checkpoint of center_param:.../下载/reid-strong-baseline-master/market_sj/resnet50_center_param_120.pth
Path to the checkpoint of optimizer_center:.../下载/reid-strong-baseline-master/market_sj/resnet50_optimizer_center_120.pth
2021-05-20 21:50:43,499 reid_baseline.train INFO: Start training
Process finished with exit code 0
为什么我按照这样改了后，直接从最后一个epoch开始，然后直接结束训练了？

**Comment by LY-cmd-xtt** [comment]
@Simplesss 
Train with center loss, the loss type is triplet_center
label smooth on, numclasses: 751
Start epoch: 120
Path to the checkpoint of optimizer:.../下载/reid-strong-baseline-master/market_sj/resnet50_optimizer_120.pth
Path to the checkpoint of center_param:.../下载/reid-strong-baseline-master/market_sj/resnet50_center_param_120.pth
Path to the checkpoint of optimizer_center:.../下载/reid-strong-baseline-master/market_sj/resnet50_optimizer_center_120.pth
2021-05-20 21:50:43,499 reid_baseline.train INFO: Start training
Process finished with exit code 0
你好，请问一下，为什么我按照你上面的方法改了之后，我再训练却显示直接从最后一个epoch开始，然后直接结束了训练？

**Comment by zhangcui2gr** [comment]
> I've solved this problem by convert
> 
> model.load_ state_ dict( torch.load ( cfg.MODEL.PRETRAIN_ PATH)) optimizer.load_ state_ dict( torch.load (path_ To_ optimizer)) to model = torch.load ( cfg.MODEL.PRETRAIN_ PATH) optimizer = torch.load (path_ To_ optimizer)

完整的改法应该是：
将作者原来的`tools/train.py`中的
`model.load_state_dict(torch.load(cfg.MODEL.PRETRAIN_PATH))`
`optimizer.load_state_dict(torch.load(path_to_optimizer))`
`center_criterion.load_state_dict(torch.load(path_to_center_param))`
`optimizer_center.load_state_dict(torch.load(path_to_optimizer_center))`

改成

`model = torch.load(cfg.MODEL.PRETRAIN_PATH)`
`optimizer = torch.load(path_to_optimizer)`
`center_criterion.load_state_dict(torch.load(path_to_center_param).state_dict())`
`optimizer_center.load_state_dict(torch.load(path_to_optimizer_center).state_dict())`
