### ISSUE TITLE
KeyError: 'model' when test model

### ISSUE THREAD

**Issue by namnguyenphuong10** [michuanhaohao/reid-strong-baseline#180]
i face a bug when i load model. 
In concretely,
`
Traceback (most recent call last):
  File "tools/test.py", line 67, in <module>
    main()
  File "tools/test.py", line 61, in main
    model.load_param(cfg.TEST.WEIGHT)
  File "./modeling/baseline.py", line 181, in load_param
    self.state_dict()[i].copy_(param_dict[i])
KeyError: 'model'
`
Has anyone ever gotten this bug and dealt this problem?

**Comment by namnguyenphuong10** [comment]
i solved this problem

`def load_param(self, trained_path):`
------`param_dict = torch.load(trained_path)`
------`for i in param_dict['model']:`
------------`if 'classifier' in i:`
------------------`continue`
------------`self.state_dict()[i].copy_(param_dict['model'][i])`

I ask permission to close this issue.
