### ISSUE TITLE
配置configs flile问题

### ISSUE THREAD

**Issue by syh-hue** [michuanhaohao/reid-strong-baseline#203]
你好，罗博士，请教一个很基础的问题。我在windows下pycharm运行，在test或者train时编辑好配置文件时，报错找不到.yml
文件，一直都是这个基础问题，不知道是什么情况。是否是环境问题，但跑其他代码没问题。
如下：
G:\syh\envs\pytorch\python.exe F:/workspace/reid-strong-baseline-master/tools/test.py --config_file configs/softmax_triplet_with_center.yml MODEL.DEVICE_ID ('0') DATASETS.NAMES ('market1501') DATASETS.ROOT_DIR ('workspace/reid-strong-baseline-master/data') MODEL.PRETRAIN_CHOICE ('self') TEST.WEIGHT ('workspace/reid-strong-baseline-master/reid/market_resnet50_model_120_rank1_945.pth')
Traceback (most recent call last):
  File "F:/workspace/reid-strong-baseline-master/tools/test.py", line 67, in <module>
    main()
  File "F:/workspace/reid-strong-baseline-master/tools/test.py", line 36, in main
    cfg.merge_from_file(args.config_file)
  File "G:\syh\envs\pytorch\lib\site-packages\yacs\config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'configs/softmax_triplet_with_center.yml'

**Comment by SuperChanS** [comment]
請問你解決了嗎
