### ISSUE TITLE
RuntimeError: './data/market1501' is not available

### ISSUE THREAD

**Issue by lucky1yday** [michuanhaohao/reid-strong-baseline#219]
I use colab to run your code. I have put the data set in the specified location, but I still throw an error. Please help me. **Thank you.**

2022-08-26 10:36:30,952 reid_baseline INFO: Using 1 GPUS
2022-08-26 10:36:30,952 reid_baseline INFO: Namespace(config_file='configs/softmax_triplet.yml', opts=['MODEL.DEVICE_ID', "('your device id')", 'DATASETS.NAMES', "('market1501')", 'OUTPUT_DIR', "('your path to save checkpoints and logs')"])
2022-08-26 10:36:30,953 reid_baseline INFO: Loaded configuration file configs/softmax_triplet.yml
2022-08-26 10:36:30,954 reid_baseline INFO: 
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/haoluo/.torch/models/resnet50-19c8e357.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "/home/haoluo/log/gu/reid_baseline_review/Opensource_test/market1501/Experiment-all-tricks-256x128-bs16x4-warmup10-erase0_5-labelsmooth_on-laststride1-bnneck_on"

2022-08-26 10:36:30,954 reid_baseline INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SAMPLER: softmax_triplet
DATASETS:
  NAMES: market1501
  ROOT_DIR: ./data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  DEVICE: cuda
  DEVICE_ID: your device id
  IF_LABELSMOOTH: on
  IF_WITH_CENTER: no
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: triplet
  NAME: resnet50
  NECK: bnneck
  PRETRAIN_CHOICE: imagenet
  PRETRAIN_PATH: /home/haoluo/.torch/models/resnet50-19c8e357.pth
OUTPUT_DIR: your path to save checkpoints and logs
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 40
  CLUSTER_MARGIN: 0.3
  EVAL_PERIOD: 40
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LOG_PERIOD: 20
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: Adam
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_K: 2
  RANGE_LOSS_WEIGHT: 1
  RANGE_MARGIN: 0.3
  STEPS: (40, 70)
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  FEAT_NORM: yes
  IMS_PER_BATCH: 128
  NECK_FEAT: after
  RE_RANKING: no
  WEIGHT: path
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main()
  File "tools/train.py", line 154, in main
    train(cfg)
  File "tools/train.py", line 27, in train
    train_loader, val_loader, num_query, num_classes = make_data_loader(cfg)
  File "./data/build.py", line 23, in make_data_loader
    dataset = init_dataset(cfg.DATASETS.NAMES, root=cfg.DATASETS.ROOT_DIR)
  File "./data/datasets/__init__.py", line 29, in init_dataset
    return __factory[name](*args, **kwargs)
  File "./data/datasets/market1501.py", line 35, in __init__
    self._check_before_run()
  File "./data/datasets/market1501.py", line 56, in _check_before_run
    raise RuntimeError("'{}' is not available".format(self.dataset_dir))
RuntimeError: './data/market1501' is not available

**Comment by WANGCHAO1996** [comment]
请问怎么解决的

**Comment by ikol5263** [comment]
I have this problem too

**Comment by ikol5263** [comment]
have you solved it?

**Comment by kun2001github** [comment]
Hi, I also encountered the same problem, please solve it?
