### ISSUE TITLE
TypeError: 'no_grad' object is not callable

### ISSUE THREAD

**Issue by shuxjweb** [michuanhaohao/reid-strong-baseline#23]
Traceback (most recent call last):
  File "/home/shuxj/tool/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/shuxj/tool/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/shuxj/tool/pycharm-community-2018.1.4/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/shuxj/tool/pycharm-community-2018.1.4/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/shuxj/work/code/PersonReID/strong_baseline/strong/tools/train.py", line 17, in <module>
    from engine.trainer import do_train, do_train_with_center
  File "/home/shuxj/work/code/PersonReID/strong_baseline/strong/engine/trainer.py", line 13, in <module>
    from ignite.metrics import RunningAverage
  File "/usr/local/lib/python3.5/dist-packages/ignite/metrics/__init__.py", line 1, in <module>
    from ignite.metrics.binary_accuracy import BinaryAccuracy
  File "/usr/local/lib/python3.5/dist-packages/ignite/metrics/binary_accuracy.py", line 4, in <module>
    from ignite.metrics.accuracy import Accuracy
  File "/usr/local/lib/python3.5/dist-packages/ignite/metrics/accuracy.py", line 5, in <module>
    from ignite.metrics.metric import Metric
  File "/usr/local/lib/python3.5/dist-packages/ignite/metrics/metric.py", line 7, in <module>
    class Metric(with_metaclass(ABCMeta, object)):
  File "/usr/local/lib/python3.5/dist-packages/ignite/metrics/metric.py", line 62, in Metric
    @torch.no_grad()
TypeError: 'no_grad' object is not callable

请问：跑您的train.py代码出现该错误，一直没找到解决办法，这是什么原因？谢谢

**Comment by michuanhaohao** [comment]
@shuxjweb 我猜测是pytorch版本没有使用1.0版本的原因，建议自己先谷歌搜索一下，如果解决不来再发issue

https://github.com/pytorch/ignite/issues/345

**Comment by shuxjweb** [comment]
好，多谢
