### ISSUE TITLE
断点训练问题

### ISSUE THREAD

**Issue by LilySys** [michuanhaohao/reid-strong-baseline#83]
罗博士，你好，我从断点开始训练，报下面的错误
Traceback (most recent call last):
  File "/home/wenli/.vscode-server/extensions/ms-python.python-2019.9.34911/pythonFiles/ptvsd_launcher.py", line 43, in <module>
    main(ptvsdArgs)
  File "/home/wenli/.vscode-server/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 432, in main
    run()
  File "/home/wenli/.vscode-server/extensions/ms-python.python-2019.9.34911/pythonFiles/lib/python/ptvsd/__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "/home/wenli/anaconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/wenli/anaconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/wenli/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/wenli/.pytorch_project/person_reid/reid-strong-baseline/tools/train.py", line 162, in <module>
    main()
  File "/home/wenli/.pytorch_project/person_reid/reid-strong-baseline/tools/train.py", line 158, in main
    train(cfg)
  File "/home/wenli/.pytorch_project/person_reid/reid-strong-baseline/tools/train.py", line 71, in train
    start_epoch     # add for using self trained model
  File "/home/wenli/.pytorch_project/person_reid/reid-strong-baseline/engine/trainer.py", line 214, in do_train
    trainer.run(train_loader, max_epochs=epochs)
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 365, in run
    self._handle_exception(e)
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 326, in _handle_exception
    raise e
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 350, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 315, in _run_once_on_dataset
    self._handle_exception(e)
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 326, in _handle_exception
    raise e
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/ignite/engine/engine.py", line 307, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "/home/wenli/.pytorch_project/person_reid/reid-strong-baseline/engine/trainer.py", line 51, in _update
    optimizer.step()
  File "/home/wenli/anaconda3/lib/python3.6/site-packages/torch/optim/adam.py", line 94, in step
    exp_avg.mul_(beta1).add_(1 - beta1, grad)
RuntimeError: expected type torch.FloatTensor but got torch.cuda.FloatTensor

**Comment by michuanhaohao** [comment]
torch.FloatTensor but got torch.cuda.FloatTensor

是这样的，pytorch模型分为gpu和cpu，如果你存的是cpu模型，就要cpu加载，如果存的是gpu模型，就要.cuda加载

**Comment by LilySys** [comment]
好的，非常非常感谢你耐心的解答。

**Comment by liuchanfeng165** [comment]
> 好的，非常非常感谢你耐心的解答。

你好解决了吗，这个模型保存是cpu的，但加载默认CPU，所以冲突，但不知道这个训练放在哪个部分，repo搞得不好，分开模型。

**Comment by liuchanfeng165** [comment]
用了另外方法解决。但保存state_dict()参数模型后再加载出错，究竟怎么设置保持导正确导入？本来就是GPU运算，怎么给我加载出错，CPU运算？哪位知道这个engine怎么设置，准确导入训练好的参数（非全部模型），麻烦告知。

**Comment by finger-monkey** [comment]
> 好的，非常非常感谢你耐心的解答。

 可以请教一下您，如何进行断点训练吗？
