### ISSUE TITLE
how to train my dataset

### ISSUE THREAD

**Issue by jerry-chenrb** [michuanhaohao/reid-strong-baseline#89]
if my dataset is not mentioned in your code，how to train it?

**Comment by michuanhaohao** [comment]
Please refer files in reid-strong-baseline/data/datasets/. You can write a .py file for your own dataset.

**Comment by Ehsan-Yaghoubi** [comment]
`**RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151**`

I want to train the network on the RAP dataset. I have created a `rap.py` as to below. I tried to mimic the `market1501.py`. When the training starts, it runs to a `RunTimeError`. I debugged the code, and I think everything goes on exactly like `market1501.py`, but I don't know the reason for this error. The error comes from `forward` function in `triplet_loss.py`, where we have:` targets = torch.zeros(log_probs.size()).scatter_(1, targets.unsqueeze(1).data.cpu(), 1)`

I debugged and realized that the size of `inputs` is `[8, 1295]` and the size of `targets` is` [8]`, (when I debug the code for `market1501`, these sizes are `[8, 751] `and `[8]`, respectively). I should add that, `batch size` is `8`, number of `ids` in RAP and market1501 are `1295` and `751` respectively. Changing the `images' size` and `batch size` do not help.

The code for rap dataset (`rap.py` ) is as follows:
```
import re
import os
from .bases import BaseImageDataset
import mat4py

class RAP (BaseImageDataset):

    dataset_dir = '/media/ehsan/48BE4782BE476810/AA_GITHUP/Anchor_Level_Paper/RAP_resized_imgs'
    RAP_reid_mat_file_path = '/media/ehsan/48BE4782BE476810/AA_GITHUP/Anchor_Level_Paper/rap_annotations/RAP_ReId_information.mat'

    def __init__(self, verbose=True, **kwargs):
        super(RAP, self).__init__()
        self._check_before_run()

        train, query, gallery = self._process_dir(self.RAP_reid_mat_file_path, self.dataset_dir)

        self.train = train
        self.query = query
        self.gallery = gallery

        if verbose:
            print("=> RAP is loaded")
            self.print_dataset_statistics(train, query, gallery)

        self.num_train_pids, self.num_train_imgs, self.num_train_cams = self.get_imagedata_info(self.train)
        self.num_query_pids, self.num_query_imgs, self.num_query_cams = self.get_imagedata_info(self.query)
        self.num_gallery_pids, self.num_gallery_imgs, self.num_gallery_cams = self.get_imagedata_info(self.gallery)


    def _check_before_run(self):
        """Check if all files are available before going deeper"""
        if not os.path.exists(self.dataset_dir):
            raise RuntimeError("'{}' is not available".format(self.dataset_dir))
        if not os.path.exists(self.RAP_reid_mat_file_path):
            raise RuntimeError("'{}' is not available".format(self.RAP_reid_mat_file_path))

    def _process_dir(self, mat_dir_path, data_dir):
        RAP_reid_information = mat4py.loadmat(filename=mat_dir_path)
        RAP_reid_information__ = mat4py.loadmat(filename="/media/ehsan/48BE4782BE476810/AA_GITHUP/Anchor_Level_Paper/rap_annotations/RAP_annotation.mat")
        image_names_ = RAP_reid_information["image_name"]
        image_names__ = RAP_reid_information__["RAP_annotation"]["name"]
        image_names_star = [subsub for sub in image_names__ for subsub in sub]
        image_names = [subsub for sub in image_names_ for subsub in sub]
        pids = RAP_reid_information["person_id"]
        # cams = RAP_reid_information["person_cam"]
        # train_ids = RAP_reid_information["train_identity"]
        # test_ids = RAP_reid_information["test_identity"]
        train_indices_ = RAP_reid_information["train_index"]
        train_indices = [subsub for sub in train_indices_ for subsub in sub]
        gallery_indices_ = RAP_reid_information["test_index"]
        gallery_indices = [subsub for sub in gallery_indices_ for subsub in sub]
        query_indices = RAP_reid_information["query_index"]


        train = []
        for i, IMG_index in enumerate(train_indices):
            img_name = image_names[IMG_index-1]
            img_full_path = os.path.join(data_dir, img_name)
            person_id = pids[IMG_index-1][0]
            camera_id = img_name.split("-")[0] # e.g. ['CAM01', '2014', '02', '15', '20140215161032', '20140215162620', 'tarid0', 'frame218', 'line1.png']
            train.append((img_full_path, person_id , int(re.findall('\d+',camera_id)[0])))

        train_star = []
        for i, IMG_index in enumerate(train_indices):
            img_name = image_names_star[IMG_index-1]
            img_full_path = os.path.join(data_dir, img_name)
            person_id = pids[IMG_index-1][0]
            camera_id = img_name.split("-")[0] # e.g. ['CAM01', '2014', '02', '15', '20140215161032', '20140215162620', 'tarid0', 'frame218', 'line1.png']
            train_star.append((img_full_path, person_id , int(re.findall('\d+',camera_id)[0])))

        query = []
        for i, IMG_index in enumerate(query_indices):
            img_name = image_names[IMG_index-1]
            img_full_path = os.path.join(data_dir, img_name)
            person_id = pids[IMG_index-1][0]
            camera_id = img_name.split("-")[0]
            query.append((img_full_path, person_id , int(re.findall('\d+',camera_id)[0])))

        gallery = []
        for i, IMG_index in enumerate(gallery_indices):
            img_name = image_names[IMG_index-1]
            img_full_path = os.path.join(data_dir, img_name)
            person_id = pids[IMG_index-1][0]
            camera_id = img_name.split("-")[0]
            gallery.append((img_full_path, person_id , int(re.findall('\d+',camera_id)[0])))

        return  train, query, gallery
```


**ERROR tracebak:**

```
Traceback (most recent call last):
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/train.py", line 154, in <module>
    main()
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/train.py", line 150, in main
    train(cfg)
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/tools/train.py", line 68, in train
    start_epoch     # add for using self trained model
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/engine/trainer.py", line 208, in do_train
    trainer.run(train_loader, max_epochs=epochs)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 326, in run
    self._handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 313, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 280, in _run_once_on_dataset
    self._handle_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 291, in _handle_exception
    raise e
  File "/usr/local/lib/python3.5/dist-packages/ignite/engine/engine.py", line 272, in _run_once_on_dataset
    self.state.output = self._process_function(self, batch)
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/engine/trainer.py", line 47, in _update
    loss = loss_fn(score, feat, target)
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/layers/__init__.py", line 35, in loss_func
    return xent(score, target) + triplet(feat, target)[0]
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/ehsan/48BE4782BE476810/AA_GITHUP/forked_reid_baseline/layers/triplet_loss.py", line 154, in forward
    targets = torch.zeros(log_probs.size()).scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
RuntimeError: Invalid index in scatter at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:151
```

**Logs/initialization:**

```
2019-12-04 10:01:26,619 reid_baseline INFO: Using 1 GPUS
2019-12-04 10:01:26,619 reid_baseline INFO: Namespace(config_file='../configs/softmax_triplet.yml', opts=[])
2019-12-04 10:01:26,619 reid_baseline INFO: Loaded configuration file ../configs/softmax_triplet.yml
2019-12-04 10:01:26,619 reid_baseline INFO: 
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/eshan/.torch/models/resnet50-19c8e357.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'




INPUT:
  SIZE_TRAIN: [128, 128]  # SIZE_TRAIN: [256, 128]
  SIZE_TEST: [128, 128]   # SIZE_TEST: [256, 128]

  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('RAP') # NAMES: ('market1501')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 8

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "path"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'

OUTPUT_DIR: "/media/ehsan/HDD2TB/PersonReIdentification/reid-strong-baseline/reid_on_RAP_RESULTS"


2019-12-04 10:01:26,619 reid_baseline INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  SAMPLER: softmax_triplet
DATASETS:
  NAMES: RAP
  ROOT_DIR: /media/ehsan/HDD2TB/PersonReIdentification/DATASET_Person_Reidentification
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [128, 128]
  SIZE_TRAIN: [128, 128]
MODEL:
  DEVICE: cuda
  DEVICE_ID: 0
  IF_LABELSMOOTH: on
  IF_WITH_CENTER: no
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: triplet
  NAME: resnet50
  NECK: bnneck
  PRETRAIN_CHOICE: imagenet
  PRETRAIN_PATH: /home/eshan/.torch/models/resnet50-19c8e357.pth
OUTPUT_DIR: /media/ehsan/HDD2TB/PersonReIdentification/reid-strong-baseline/reid_on_RAP_RESULTS
SOLVER:
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 40
  CLUSTER_MARGIN: 0.3
  EVAL_PERIOD: 40
  GAMMA: 0.1
  IMS_PER_BATCH: 8
  LOG_PERIOD: 20
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: Adam
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_K: 2
  RANGE_LOSS_WEIGHT: 1
  RANGE_MARGIN: 0.3
  STEPS: (40, 70)
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
TEST:
  FEAT_NORM: yes
  IMS_PER_BATCH: 128
  NECK_FEAT: after
  RE_RANKING: no
  WEIGHT: path
=> RAP is loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |  1295 |    13178 |        23
  query    |  1294 |     7202 |        23
  gallery  |  1295 |    28407 |        23
  ----------------------------------------
Loading pretrained ImageNet model......
Train without center loss, the loss type is triplet
label smooth on, numclasses: 1295
2019-12-04 10:01:32,222 reid_baseline.train INFO: Start training


```
